### ISSUE TITLE
Disable tracking while in development

### ISSUE THREAD

**Issue by hslee2008** [johannschopplich/nuxt-gtag#44]
### Describe the feature

Maybe in `nuxt.config.ts`, define `disableDuringDevelopment` module option to disable gtag tracking during development.

I'm not sure if there is any other ways of doing this, so if you know how to disable tracking with another way, please tell me.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-gtag/issues).

**Comment by johannschopplich** [comment]
What about you keep the `id` property if the module configuration empty and add the Gtag ID via a runtime config variable only in production? Does this solve your issue?

```ini
// Only add this in production
NUXT_PUBLIC_GTAG_ID=G-XXXXXXXXXX
```
